'use client';
import { useEffect, useState } from 'react';
import { ArrowUpRight, Minus, Plus, Scan, X } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogDescription, DialogTitle } from '@/components/ui/dialog';
import { ToggleGroup, ToggleGroupItem } from '@/components/ui/toggle-group';
import { base } from '@/lib/portfolio';
const scales = [
  { id: 'colony', label: '01 / Colony', image: 'ant-ground.png', ratio: 1.5, title: 'A different way of finding a path.', text: 'Ant Scape begins with the collective behavior of ants: small movements and local interactions that suggest another way to organize a city.', credit: 'Concept illustration', position: { x: .48, y: .60 } },
  { id: 'algorithm', label: '02 / Algorithm', image: 'ant-algorithm.webp', ratio: 1510 / 690, title: 'From local traces to an emerging network.', text: 'The portfolio studies stigmergy-driven agents, testing how food sources and obstacles change the paths that emerge.', credit: 'Ant Scape · Algorithm studies · 2021', position: { x: .34, y: .36 } },
  { id: 'city', label: '03 / City', image: 'ant-city.webp', ratio: 2400 / 1698, title: 'Imagine moving through the city of ants.', text: 'The project carries these networks into urban form, exploring mobility, pathways, and spaces from a non-human perspective.', credit: 'Ant Scape · Urban design studies · Lisbon · 2021', position: { x: .5, y: .5 } },
];
export function AntLens({ open, onClose, onPortfolio }: { open: boolean; onClose: () => void; onPortfolio: () => void }) {
  const [scale, setScale] = useState('colony');
  const [lens, setLens] = useState(true);
  const [zoom, setZoom] = useState(3);
  const [point, setPoint] = useState({ x: .48, y: .60 });
  const [frame, setFrame] = useState<HTMLDivElement | null>(null);
  const [size, setSize] = useState({ width: 900, height: 600 });
  const current = scales.find(item => item.id === scale)!;
  useEffect(() => { if(!frame)return; const observer = new ResizeObserver(([entry]) => setSize({ width: entry.contentRect.width, height: entry.contentRect.height })); observer.observe(frame); return () => observer.disconnect(); },[frame]);
  const diameter = size.width < 500 ? 150 : 215;
  const place = (event: React.PointerEvent<HTMLDivElement>) => { const rect = event.currentTarget.getBoundingClientRect(); setPoint({ x: Math.max(0, Math.min(1, (event.clientX - rect.left) / rect.width)), y: Math.max(0, Math.min(1, (event.clientY - rect.top) / rect.height)) }); };
  return <Dialog open={open} onOpenChange={value => {if(!value)onClose();}}><DialogContent className="ant-dialog" showCloseButton={false}><header className="ant-header"><div><p className="eyebrow">Ant Scape / Across scales</p><DialogTitle>{current.title}</DialogTitle><DialogDescription>{current.text}</DialogDescription></div><Button variant="ghost" size="icon" aria-label="Return to the clearing" onClick={onClose}><X size={22}/></Button></header><div className="ant-controls"><ToggleGroup value={[scale]} multiple={false} onValueChange={values => {if(values[0]) {setScale(values[0]);setPoint(scales.find(item => item.id === values[0])!.position);}}} aria-label="Explore Ant Scape at different scales" className="ant-scale-switch">{scales.map(item => <ToggleGroupItem key={item.id} value={item.id}>{item.label}</ToggleGroupItem>)}</ToggleGroup><div className="lens-controls"><Button variant="ghost" aria-pressed={lens} onClick={() => setLens(!lens)}><Scan size={16}/> Lens</Button><Button variant="ghost" size="icon" aria-label="Reduce magnification" disabled={zoom === 2} onClick={() => setZoom(zoom - 1)}><Minus size={15}/></Button><span>{zoom}×</span><Button variant="ghost" size="icon" aria-label="Increase magnification" disabled={zoom === 6} onClick={() => setZoom(zoom + 1)}><Plus size={15}/></Button></div></div><div className="ant-stage"><div ref={setFrame} className={`ant-image-frame ${lens ? 'lens-enabled' : ''}`} style={{ aspectRatio: current.ratio, width: `min(100%, calc((100dvh - 265px) * ${current.ratio}))` }} role="region" tabIndex={0} aria-label="Magnifying view. Move your pointer or touch to inspect; use arrow keys to move the lens." onPointerMove={place} onPointerDown={event => {place(event);event.currentTarget.setPointerCapture(event.pointerId);}} onKeyDown={event => { const delta: Record<string, [number, number]> = { ArrowLeft: [-.035,0], ArrowRight: [.035,0], ArrowUp: [0,-.035], ArrowDown: [0,.035] }; if(delta[event.key]) {event.preventDefault();const [x,y]=delta[event.key];setPoint(old => ({ x: Math.max(0,Math.min(1,old.x+x)), y: Math.max(0,Math.min(1,old.y+y)) }));} }}><img className="ant-source" src={`${base}/images/${current.image}`} alt={current.credit} draggable={false}/>{lens && <div className="ant-magnifier" style={{ left: point.x * size.width, top: point.y * size.height, width: diameter, height: diameter }} aria-hidden="true"><img src={`${base}/images/${current.image}`} alt="" draggable={false} style={{ width: size.width * zoom, height: size.height * zoom, left: diameter / 2 - point.x * size.width * zoom, top: diameter / 2 - point.y * size.height * zoom }}/><span>{zoom}×</span></div>}</div></div><footer className="ant-footer"><span>Move the lens to look closer.</span><span>{current.credit}</span><Button variant="ghost" className="text-action" onClick={onPortfolio}>View Ant Scape <ArrowUpRight size={16}/></Button></footer></DialogContent></Dialog>;
}
