'use client';
import { useState } from 'react';
import { ArrowRight, ArrowUpRight, BookOpen, Download, X } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { ToggleGroup, ToggleGroupItem } from '@/components/ui/toggle-group';
import { base } from '@/lib/portfolio';
import { paper, landSettings, paperFigures, figureImage } from '@/lib/research';

export function ResearchSection({ onOpen, onAcademic }: { onOpen: (id: 'wildfire' | 'defensible') => void; onAcademic: () => void }) {
  return <section id="research-work" className="selected-work research-section">
    <div className="section-heading"><div><p className="eyebrow">Current work</p><h2 className="display-heading">Research</h2></div><Button variant="ghost" className="text-action" onClick={onAcademic}>Academic index <ArrowUpRight size={16}/></Button></div>
    <article className="research-lead"><div className="research-lead-copy"><p className="eyebrow">Environmental Research Letters · 2026</p><h3>{paper.title}</h3><p className="research-deck">Compound hazards, urban cascades, and the places research overlooks.</p><p>A global synthesis of 3,625 studies connects the research record with fire occurrence, climate conditions, and social vulnerability.</p><Button className="research-read" onClick={() => onOpen('wildfire')}>Read the research <ArrowRight size={17}/></Button><span className="research-byline">Xinyi Zhang & Lu Liang</span></div><button className="research-lead-art" onClick={() => onOpen('wildfire')} aria-label="Explore the global research-risk mismatch"><img src={figureImage(7)} alt="Published maps of the mismatch between global fire burden, research attention, and social vulnerability." loading="lazy"/><span>Where fire, vulnerability, and research diverge <ArrowUpRight size={16}/></span></button></article>
    <article className="research-ongoing"><button onClick={() => onOpen('defensible')} aria-label="Open Where the Fire Stopped"><img src={`${base}/images/defensible-design.jpg`} alt="Evidence-informed defensible space design alternatives." loading="lazy"/></button><div><p className="eyebrow">Research in progress</p><h3>Where the Fire Stopped</h3><p>From post-fire evidence to defensible space design. A study of 7,122 single-family homes in the 2025 Eaton Fire.</p><Button variant="ghost" className="text-action" onClick={() => onOpen('defensible')}>Explore the project <ArrowRight size={16}/></Button></div></article>
  </section>;
}
function MismatchComparison() {
  const [setting, setSetting] = useState('wui');
  const current = landSettings.find(item => item.id === setting)!;
  return <section className="mismatch-comparison"><p className="eyebrow">Research attention / Fire occurrence</p><h3>Two very different distributions.</h3><ToggleGroup value={[setting]} multiple={false} onValueChange={values => { if(values[0])setSetting(values[0]); }} aria-label="Compare land settings" className="setting-switch">{landSettings.map(item => <ToggleGroupItem key={item.id} value={item.id}>{item.title}</ToggleGroupItem>)}</ToggleGroup><div className="comparison-bars" aria-live="polite"><div><span>Share of global fire occurrence</span><strong>{current.fire}%</strong><div className="comparison-track"><span style={{ width: `${current.fire}%` }}/></div></div><div><span>Share of the research corpus</span><strong>{current.research}%</strong><div className="comparison-track research-track"><span style={{ width: `${current.research}%` }}/></div></div><p>{current.note}</p></div><p className="figure-source">Source: section 6.1 and figure 8. Fire occurrence and publication share have separate denominators.</p></section>;
}
export function ResearchReader({ open, onClose }: { open: boolean; onClose: () => void }) {
  const [tab, setTab] = useState('overview');
  const [figure, setFigure] = useState(7);
  const [pdfPage, setPdfPage] = useState(1);
  const current = paperFigures[figure - 1];
  function readFigure(number: number) { setFigure(number); setTab('figures'); }
  return <Dialog open={open} onOpenChange={value => { if(!value)onClose(); }}><DialogContent className="research-dialog" showCloseButton={false}>
    <header className="research-reader-header"><div><p className="eyebrow">Environmental Research Letters · 21, 133007 · 8 July 2026</p><DialogTitle>{paper.title}</DialogTitle><DialogDescription>{paper.authors}</DialogDescription></div><Button variant="ghost" size="icon" aria-label="Close research" onClick={onClose}><X size={22}/></Button></header>
    <Tabs value={tab} onValueChange={setTab} className="research-reader-tabs"><div className="research-reader-nav"><TabsList aria-label="Read research" className="reader-tab-list"><TabsTrigger value="overview">Overview</TabsTrigger><TabsTrigger value="figures">Figures</TabsTrigger><TabsTrigger value="paper">Full paper</TabsTrigger></TabsList><a href={paper.pdf} download><Download size={16}/><span>PDF</span></a></div>
      <TabsContent value="overview" className="research-overview"><div className="paper-opening"><p className="paper-subtitle">{paper.subtitle}</p><p className="paper-opening-text">Wildfire-linked risks extend beyond the burn perimeter, through cities, infrastructure, and unequal patterns of exposure.</p><div className="paper-facts"><div><strong>3,625</strong><span>studies reviewed</span></div><div><strong>2000–2025</strong><span>literature coverage</span></div><div><strong>Global</strong><span>spatial risk analysis</span></div></div></div><MismatchComparison/>
      <div className="paper-findings"><article><span className="eyebrow">01 / Compound conditions</span><h3>Risk changes when climate extremes coincide.</h3><p>Heat, drought, and wind do not act independently. Compound conditions are associated with stronger wildfire risk amplification, with especially pronounced responses in urban settings.</p><button onClick={() => readFigure(9)}>Explore compound risk <ArrowRight size={16}/></button></article><article><span className="eyebrow">02 / Uneven attention</span><h3>Research misses many of the places most exposed.</h3><p>Fire burden, low research coverage, and social vulnerability converge most severely in the Global South. The WUI has the highest combined mismatch across land settings.</p><button onClick={() => readFigure(7)}>Explore the global maps <ArrowRight size={16}/></button></article><article><span className="eyebrow">03 / Urban cascades</span><h3>The evidence thins as impacts travel through cities.</h3><p>Smoke, post-fire debris flows, and infrastructure disruption connect fire to urban life. The review finds particularly little evidence linking damaged infrastructure to the loss of essential services.</p><button onClick={() => readFigure(10)}>Follow the evidence chain <ArrowRight size={16}/></button></article></div>
      <figure className="paper-overview-figure"><button onClick={() => readFigure(10)} aria-label="View figure 10"><img src={figureImage(10)} alt={paperFigures[9].caption} loading="lazy"/></button><figcaption>Figure 10 · {paperFigures[9].caption}</figcaption></figure>
      <section className="paper-methods"><h3>How the study was conducted</h3><p>The review combines LLM-assisted classification of Web of Science records with global spatial analysis using MODIS burned area, ERA5-Land climate, WUI mapping, and the Global Gridded Relative Deprivation Index. Classification was checked against a targeted set of 350 high-ambiguity records.</p><h3>Reading the findings</h3><p>Literature coding uses abstracts and may undercount themes discussed only in full texts. Spatial footprints and gridded data limit local precision. Relative-risk estimates describe annual co-occurrence across 2001–2024, rather than event-scale causal effects; satellite data can miss small and low-intensity fires.</p></section>
      <section className="paper-abstract"><h3>Abstract</h3><p>{paper.abstract}</p></section><div className="paper-citation"><p>{paper.citation}</p><a href={paper.doi} target="_blank" rel="noreferrer">Publisher’s article <ArrowUpRight size={14}/></a><span>© 2026 The authors. Article and figures: CC BY 4.0. Figure captions on this page are condensed.</span></div></TabsContent>
      <TabsContent value="figures" className="research-figures"><nav className="figure-index" aria-label="Choose a research figure">{paperFigures.map(item => <button key={item.number} aria-current={figure === item.number ? 'true' : undefined} onClick={() => setFigure(item.number)}><span>{String(item.number).padStart(2,'0')}</span>{item.title}</button>)}</nav><figure className="figure-detail"><div><span className="eyebrow">Figure {current.number}</span><h3>{current.title}</h3></div><a href={figureImage(figure)} target="_blank" rel="noreferrer" aria-label="Open figure at full resolution"><img src={figureImage(figure)} alt={current.caption}/></a><figcaption>{current.caption}</figcaption><Button variant="ghost" className="text-action" onClick={() => {setPdfPage(current.page);setTab('paper');}}>Read in the paper <BookOpen size={15}/></Button><p className="figure-source">Zhang & Liang (2026), Environmental Research Letters 21, 133007 · CC BY 4.0</p></figure></TabsContent>
      <TabsContent value="paper" className="research-full-paper"><a className="pdf-fallback" href={`${paper.pdf}#page=${pdfPage}`} target="_blank" rel="noreferrer">Open full paper in a new tab <ArrowUpRight size={16}/></a><iframe key={pdfPage} src={`${paper.pdf}#page=${pdfPage}&view=FitH`} title="Wildfire as urban risk — full published article"/></TabsContent>
    </Tabs>
  </DialogContent></Dialog>;
}
