'use client';
import { useEffect, useState } from 'react';
import { ArrowDown, ArrowRight, ArrowUpRight, BookOpen, Map, Plus, X } from 'lucide-react';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { Sheet, SheetContent, SheetTitle, SheetDescription } from '@/components/ui/sheet';
import { Button } from '@/components/ui/button';

type View = 'explore' | 'academic';
type Entry = 'wildfire' | 'defensible' | 'landscape' | 'about' | 'cv';
const base = process.env.NEXT_PUBLIC_BASE_PATH || '';
const asset = (name: string) => `${base}/images/${name}`;
const projects = [
  { id:'wildfire' as const, number:'01', category:'Published research', title:'Wildfire as urban risk', subtitle:'Global synthesis of compound hazards, cascade pathways, and research-exposure-vulnerability mismatch', question:'What happens when wildfire risk reaches beyond the burn perimeter?', description:'Investigating how wildfire-linked risks travel through urban systems, and where research attention, exposure, and vulnerability diverge.', image:'', link:'https://doi.org/10.1088/1748-9326/ae8039', linkLabel:'Read the paper', tags:['Wildfire','Urban risk','Global synthesis'] },
  { id:'defensible' as const, number:'02', category:'Research in progress', title:'Where the Fire Stopped', subtitle:'AI-driven defensible space design from post-fire evidence', question:'How can landscape evidence inform the spaces around our homes?', description:'Connecting pre-fire landscape conditions and post-fire building outcomes in the 2025 Eaton Fire with a workflow for generating and reviewing site-specific landscape alternatives.', image:'defensible-design.jpg', link:'https://xinyizh-sydnie.github.io/eaton-evidence-hub/', linkLabel:'Explore the evidence hub', tags:['Defensible space','GeoAI','Design research'] },
  { id:'landscape' as const, number:'03', category:'Selected landscape work', title:'In Seek of Homeland', subtitle:'Landscapes of memory, change, and belonging', question:'What makes a landscape feel like home?', description:'A collection of landscape architecture projects exploring water, ecology, cultural memory, and the ways people make a place their own.', image:'homeland.jpg', link:'', linkLabel:'', tags:['Landscape architecture','Urban design','Illustration'] },
];
const validEntry = (value:string | null):value is Entry => ['wildfire','defensible','landscape','about','cv'].includes(value || '');

export default function Home() {
  const [view,setView] = useState<View>('explore');
  const [selected,setSelected] = useState<Entry | null>(null);
  const [hovered,setHovered] = useState<string | null>(null);
  const [tour,setTour] = useState<number | null>(null);
  const project = projects.find(p=>p.id===selected);
  useEffect(()=>{
    const sync=()=>{ const p=new URLSearchParams(window.location.search); setView(p.get('view')==='academic'?'academic':'explore'); const e=p.get('project'); setSelected(validEntry(e)?e:null); };
    sync(); window.addEventListener('popstate',sync); return ()=>window.removeEventListener('popstate',sync);
  },[]);
  function url(nextView:View,entry:Entry|null){const u=new URL(window.location.href); nextView==='academic'?u.searchParams.set('view','academic'):u.searchParams.delete('view'); entry?u.searchParams.set('project',entry):u.searchParams.delete('project'); window.history.pushState({},'',u);}
  function changeView(value:string){ const next=value as View; setView(next);setTour(null);setHovered(null);url(next,selected); }
  function open(entry:Entry){setSelected(entry);url(view,entry);}
  function close(){setSelected(null);url(view,null);}
  function nextStop(){setTour(n=>n===null?0:(n+1)%projects.length);}
  const active=tour===null?hovered:projects[tour].id;
  return <Tabs value={view} onValueChange={changeView} className="site-shell">
    <a href="#main-content" className="skip-link">Skip to content</a>
    <header className="site-header">
      <a className="wordmark" href={base+'/'} aria-label="xyz / a clearing home"><span className="xyz">xyz<span>·</span></span><span className="divider">/</span><span className="clearing-word">a clearing</span></a>
      <nav className="main-nav" aria-label="Main navigation"><Button variant="ghost" className="nav-button" onClick={()=>open('about')}>About</Button><Button variant="ghost" className="nav-button" onClick={()=>open('cv')}>CV</Button><a className="hello-link" href="mailto:xinyi_zh@berkeley.edu">Say hello <ArrowUpRight size={15}/></a></nav>
      <TabsList className="view-switch" aria-label="Website view"><TabsTrigger className="view-button" value="explore"><Map size={14}/> Explore</TabsTrigger><TabsTrigger className="view-button" value="academic"><BookOpen size={14}/> Academic</TabsTrigger></TabsList>
    </header>
    <main id="main-content">
      <TabsContent value="explore" className="explore-view">
        <section className="clearing-scene" aria-label="Explore Xinyi Zhang's work">
          <div className="intro"><p className="eyebrow">Xinyi Zhang · UC Berkeley</p><h1>How do we live <br/>with changing <br/><em>landscapes?</em></h1><p className="intro-copy">I study wildfire and design landscapes. <br/>This is a small clearing for my <br/>research, drawings, and questions.</p><Button variant="ghost" className="walk-button" onClick={nextStop}>Take a little walk <ArrowRight size={18}/></Button></div>
          <div className={`garden ${active?'garden-focused':''}`}><img className="garden-art" src={asset('clearing.png')} width="1536" height="1024" fetchPriority="high" alt="An illustrated clearing with a small house, meadow, birch trees, and an open field notebook."/>
            <div className="garden-points">{projects.map(p=><button key={p.id} type="button" className={`garden-point point-${p.id} ${active===p.id?'is-focused':''}`} onClick={()=>open(p.id)} onMouseEnter={()=>setHovered(p.id)} onMouseLeave={()=>setHovered(null)} onFocus={()=>setHovered(p.id)} onBlur={()=>setHovered(null)} aria-label={`Explore ${p.title}`}><span className="point-anchor"><Plus size={14} strokeWidth={1.6}/></span><span className="point-caption"><span className="point-meta">{p.number} / {p.category}</span><span className="point-name">{p.title}<ArrowUpRight size={14}/></span></span></button>)}</div>
            <span className="garden-note" aria-hidden="true">a place to look<br/>a little closer</span>
          </div>
          <div className="scene-bottom"><span className="coordinates"><span className="coord-cross" aria-hidden="true">+</span> 37.87° N &nbsp; 122.26° W <span className="coordinate-location">Berkeley, California</span></span><span className="scene-hint">Choose a little place to begin <ArrowUpRight size={15}/></span><a href="#selected-work" className="scroll-link" aria-label="Scroll to selected work"><ArrowDown size={18}/></a></div>
          {tour!==null&&<div className="walk-guide" role="region" aria-live="polite" aria-label="Guided walk"><div><span className="eyebrow">A little walk · {tour+1} of 3</span><p>{projects[tour].question}</p></div><Button className="small-action" onClick={()=>open(projects[tour].id)}>Look closer <ArrowUpRight size={15}/></Button><Button variant="ghost" className="guide-next" onClick={nextStop}>Next stop <ArrowRight size={15}/></Button><Button variant="ghost" size="icon" aria-label="End guided walk" onClick={()=>setTour(null)}><X size={16}/></Button></div>}
        </section>
        <section id="selected-work" className="selected-work"><div className="section-heading"><div><p className="eyebrow">Across the clearing</p><h2>A few things I’m working on.</h2></div><Button variant="ghost" className="text-action" onClick={()=>changeView('academic')}>View research index <ArrowUpRight size={16}/></Button></div>
          <div className="work-grid"><button className="work-item" onClick={()=>open('defensible')}><div className="work-image evidence-image"><img src={asset('defensible-design.jpg')} alt="Evidence-informed design workflow and generated parcel alternatives from the research report." loading="lazy"/></div><div className="work-label"><span className="eyebrow">Research in progress · 2026</span><ArrowUpRight size={18}/></div><h3>Where the Fire Stopped</h3><p>From landscape evidence to defensible space design.</p></button><button className="work-item" onClick={()=>open('landscape')}><div className="work-image"><img src={asset('homeland.jpg')} alt="Xinyi Zhang's original Back to Homeland landscape illustration." loading="lazy"/></div><div className="work-label"><span className="eyebrow">From the design portfolio</span><ArrowUpRight size={18}/></div><h3>In Seek of Homeland</h3><p>Drawings and designs about the places we call home.</p></button></div>
          <button className="publication-strip" onClick={()=>open('wildfire')}><BookOpen className="pub-symbol" size={23}/><span><span className="eyebrow">Recently published · Environmental Research Letters</span><strong>Wildfire as urban risk</strong></span><span className="publication-year">2026</span><ArrowUpRight size={20}/></button>
        </section>
      </TabsContent>
      <TabsContent value="academic" className="academic-view">
        <div className="academic-intro"><div><p className="eyebrow">Research & practice</p><h1>Xinyi Zhang</h1><p className="academic-affiliation">PhD student in Landscape Architecture<br/>and Environmental Planning · UC Berkeley</p></div><p className="academic-statement">I work at the intersection of wildfire risk, landscape architecture, and computational design—connecting environmental evidence with the places people inhabit.</p></div>
        <div className="academic-layout"><aside className="academic-sidebar"><a href="#publications">Publications</a><a href="#current-research">Current research</a><a href="#background">Background</a><Button variant="ghost" className="text-action" onClick={()=>open('cv')}>View CV <ArrowUpRight size={14}/></Button><a href="mailto:xinyi_zh@berkeley.edu">xinyi_zh@berkeley.edu</a><div className="research-keywords"><span className="eyebrow">Research interests</span><p>Wildfire-resilient design<br/>Defensible space<br/>Wildland–urban interface<br/>Remote sensing & GeoAI<br/>Generative environmental design</p></div></aside>
          <div className="academic-body"><section id="publications"><p className="eyebrow">01 / Publications</p><article className="academic-entry"><span className="entry-year">2026</span><div><a className="paper-title" href={projects[0].link} target="_blank" rel="noreferrer">Wildfire as urban risk: global synthesis of compound hazards, cascade pathways, and research-exposure-vulnerability mismatch <ArrowUpRight size={18}/></a><p><strong>Xinyi Zhang</strong> and Lu Liang</p><p><em>Environmental Research Letters</em> · Published 8 July 2026</p><div className="entry-actions"><a href={projects[0].link} target="_blank" rel="noreferrer">Paper ↗</a><Button variant="ghost" className="inline-button" onClick={()=>open('wildfire')}>Project overview ↗</Button></div></div></article><article className="academic-entry"><span className="entry-year">Practice</span><div><h3>Playbook for the Pyrocene: Design Strategies for Fire-Prone Communities</h3><p>Contributing researcher, SWA Group · XL Lab</p><p>Literature review, strategy cataloging, and data visualization for a practitioner-facing publication.</p></div></article></section>
            <section id="current-research"><p className="eyebrow">02 / Current research</p><article className="academic-entry"><span className="entry-year">Ongoing</span><div><button className="paper-title" onClick={()=>open('defensible')}>Where the Fire Stopped <ArrowUpRight size={18}/></button><p>AI-driven defensible space design from post-fire evidence.</p><p>Pre-fire landscape conditions, structure outcomes, and evidence-informed generative design in the 2025 Eaton Fire.</p><a className="entry-link" href={projects[1].link} target="_blank" rel="noreferrer">Evidence & design hub ↗</a></div></article></section>
            <section id="background"><p className="eyebrow">03 / Background</p><div className="background-grid"><div><h3>Education</h3><p><strong>UC Berkeley</strong><br/>PhD, Landscape Architecture and Environmental Planning · 2025–present</p><p><strong>University of Pennsylvania</strong><br/>Master of Landscape Architecture and Regional Planning · 2023<br/>Certificate of Urban Design</p><p><strong>Beijing Forestry University</strong><br/>BEng, Landscape Architecture · 2021</p></div><div><h3>Selected practice</h3><p><strong>OJB Landscape Architecture</strong><br/>Sustainable Design Specialist<br/>2023–2025</p><p><strong>SWA Group · XL Lab</strong><br/>Design Researcher · 2023<br/>Intern Researcher · 2022</p><Button variant="ghost" className="text-action" onClick={()=>open('landscape')}>Explore selected design work <ArrowUpRight size={14}/></Button></div></div></section>
          </div>
        </div>
      </TabsContent>
    </main>
    <footer className="site-footer"><span>xyz / a clearing</span><span>Research, landscapes, and things in between.</span><a href="mailto:xinyi_zh@berkeley.edu">Let’s be in touch <ArrowUpRight size={14}/></a></footer>
    <Sheet open={selected!==null} onOpenChange={isOpen=>{if(!isOpen)close();}}><SheetContent className="project-sheet">
      {project?<><div className="sheet-copy"><p className="eyebrow">{project.number} / {project.category}</p><SheetTitle className="sheet-heading">{project.title}</SheetTitle><SheetDescription className="sheet-subtitle">{project.subtitle}</SheetDescription><p className="project-question">{project.question}</p><p>{project.description}</p><div className="project-tags">{project.tags.map(t=><span key={t}>{t}</span>)}</div></div>
        {project.id==='wildfire'?<div className="research-note"><p className="eyebrow">Environmental Research Letters · 2026</p><p className="research-note-title">Hazards.<br/>Pathways.<br/>Uneven exposure.</p><p>Xinyi Zhang & Lu Liang</p><a href={project.link} target="_blank" rel="noreferrer">Read the published paper <ArrowUpRight size={16}/></a></div>:<figure className="project-figure"><img src={asset(project.image)} alt={project.id==='landscape'?'Back to Homeland: original illustration by Xinyi Zhang.':'Evidence-informed design workflow and alternative parcel plans.'}/><figcaption>{project.id==='landscape'?'Back to Homeland · From the design portfolio':'Evidence-informed generative design · From the Autodesk submission'}</figcaption></figure>}
        <div className="sheet-copy">{project.id==='defensible'&&<><h3>From observation to alternatives</h3><p>The prototype connects landscape measurements, generated alternatives, independent review, and environmental comparisons. Its study includes 7,122 single-family homes within the Eaton Fire perimeter.</p><p className="project-caveat">Research prototype. Candidate designs retain their review status; they are not certified fire-safety recommendations.</p></>}
          {project.id==='wildfire'&&<><h3>Publication</h3><p>Zhang, X., & Liang, L. (2026). Wildfire as urban risk: global synthesis of compound hazards, cascade pathways, and research-exposure-vulnerability mismatch. <em>Environmental Research Letters.</em></p><p className="doi">DOI: 10.1088/1748-9326/ae8039</p></>}
          {project.id==='landscape'&&<><h3>Ways of looking at a landscape</h3><p>From <em>Living with Water</em> to <em>Back to Homeland</em>, these projects use plans, sections, maps, and illustrated scenes to explore relationships between people and place.</p><figure className="project-figure inner-figure"><img src={asset('living-with-water.jpg')} alt="Living with Water: the proposal in rainy and dry seasons." loading="lazy"/><figcaption>Living with Water · Rainy and dry seasons</figcaption></figure><figure className="project-figure inner-figure"><img src={asset('landscape-language.jpg')} alt="Back to Homeland: landscape elements and reconstruction diagrams." loading="lazy"/><figcaption>Back to Homeland · Landscape elements and reconstruction</figcaption></figure></>}
          {project.link&&<a className="external-button" href={project.link} target="_blank" rel="noreferrer">{project.linkLabel}<ArrowUpRight size={17}/></a>}<div className="next-project"><span className="eyebrow">Continue exploring</span><button onClick={()=>open(projects[(projects.indexOf(project)+1)%projects.length].id)}>{projects[(projects.indexOf(project)+1)%projects.length].title}<ArrowRight size={17}/></button></div></div>
      </>:<div className="sheet-copy about-copy"><p className="eyebrow">{selected==='cv'?'Curriculum vitae · Selected background':'A little about me'}</p><SheetTitle className="sheet-heading">Xinyi Zhang</SheetTitle><SheetDescription className="sheet-subtitle">Landscape researcher & designer<br/>PhD student · UC Berkeley</SheetDescription><p>I study how landscapes shape wildfire risk and how environmental evidence can inform design. My work brings together landscape architecture, remote sensing, GeoAI, and generative methods.</p><p>Before beginning my PhD, I worked in landscape practice and design research with OJB and SWA Group’s XL Lab.</p><h3>Education</h3><p>UC Berkeley · PhD in Landscape Architecture and Environmental Planning, 2025–present</p><p>University of Pennsylvania · Master of Landscape Architecture and Regional Planning, 2023; Certificate of Urban Design</p><p>Beijing Forestry University · BEng in Landscape Architecture, 2021</p><h3>Research & practice</h3><p>UC Berkeley · Graduate Researcher, 2025–present<br/>OJB Landscape Architecture · Sustainable Design Specialist, 2023–2025<br/>SWA Group, XL Lab · Design Researcher, 2023; Intern Researcher, 2022</p><h3>Advisors</h3><p>Danielle Rivera and Lu Liang</p><a className="external-button" href="mailto:xinyi_zh@berkeley.edu">xinyi_zh@berkeley.edu <ArrowUpRight size={17}/></a><button className="text-action about-index" onClick={()=>{setSelected(null);setView('academic');url('academic',null);}}>View publications & research <ArrowRight size={16}/></button></div>}
    </SheetContent></Sheet>
  </Tabs>;
}
